/**
 * Application Error Codes
 *
 * Every error returned by the API uses one of these codes.
 * Codes are stable — they form part of the public API contract.
 * Clients can switch on these codes for programmatic error handling.
 */

export enum ErrorCode {
  // -- Client errors (4xx) --
  BAD_REQUEST = "BAD_REQUEST",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  GONE = "GONE",
  UNPROCESSABLE = "UNPROCESSABLE",
  RATE_LIMITED = "RATE_LIMITED",
  IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT",

  // -- Business logic errors --
  LESSON_ALREADY_COMPLETED = "LESSON_ALREADY_COMPLETED",
  LAB_SESSION_ACTIVE = "LAB_SESSION_ACTIVE",
  LAB_VALIDATION_IN_PROGRESS = "LAB_VALIDATION_IN_PROGRESS",
  LAB_SESSION_EXPIRED = "LAB_SESSION_EXPIRED",
  QUIZ_ALREADY_SUBMITTED = "QUIZ_ALREADY_SUBMITTED",
  STREAK_FREEZE_UNAVAILABLE = "STREAK_FREEZE_UNAVAILABLE",
  EXPORT_LIMIT_REACHED = "EXPORT_LIMIT_REACHED",
  INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION",
  MODULE_NOT_COMPLETED = "MODULE_NOT_COMPLETED",
  PATH_NOT_COMPLETED = "PATH_NOT_COMPLETED",

  // -- Server errors (5xx) --
  INTERNAL_ERROR = "INTERNAL_ERROR",
  DATABASE_ERROR = "DATABASE_ERROR",
  CACHE_ERROR = "CACHE_ERROR",
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  QUEUE_ERROR = "QUEUE_ERROR",
}
