/**
 * Middleware Type Definitions
 *
 * Defines the middleware pipeline type system.
 * All middleware follows a composable higher-order function pattern.
 */

import { NextRequest } from "next/server";
import type { Role, Scope, Resource, Action } from "@/lib/auth/rbac";

// ---------------------------------------------------------------------------
// Request context — accumulated by middleware, consumed by handlers
// ---------------------------------------------------------------------------

export interface RequestContext {
  /** Unique request ID for tracing (generated by logging middleware) */
  requestId: string;

  /** Authenticated user context (set by auth middleware) */
  user?: AuthenticatedUser;

  /** Validated request body (set by validation middleware) */
  body?: unknown;

  /** Request start time (set by logging middleware) */
  startTime: number;
}

export interface AuthenticatedUser {
  /** Clerk user ID */
  clerkId: string;

  /** Supabase profile UUID */
  profileId: string;

  /** User's current role */
  role: Role;

  /** Populated for trainer/institute_admin */
  instituteId?: string;

  /** Populated for recruiter/org_admin */
  orgId?: string;
}

// ---------------------------------------------------------------------------
// Handler and middleware types
// ---------------------------------------------------------------------------

/** A route handler receives the raw request and accumulated context */
export type RouteHandler = (
  req: NextRequest,
  ctx: RequestContext
) => Promise<Response>;

/** A middleware wraps a handler, adding behavior before/after */
export type Middleware = (handler: RouteHandler) => RouteHandler;

// ---------------------------------------------------------------------------
// Middleware configuration types
// ---------------------------------------------------------------------------

export type RateLimitTier =
  | "auth"
  | "progress"
  | "events"
  | "labs"
  | "search"
  | "reports"
  | "global";

export interface RateLimitConfig {
  tier: RateLimitTier;
  /** Override the default limit for this tier */
  limit?: number;
  /** Override the default window for this tier */
  windowSeconds?: number;
}

export interface RbacConfig {
  resource: Resource;
  action: Action;
  scope?: Scope;
}

// ---------------------------------------------------------------------------
// Protected route shorthand
// ---------------------------------------------------------------------------

export interface ProtectedRouteConfig {
  /** Rate limit tier */
  rateLimit?: RateLimitTier | RateLimitConfig;

  /** RBAC permission check */
  permission?: RbacConfig;

  /** Zod schema for request body validation */
  schema?: import("zod").ZodType;

  /** The actual request handler */
  handler: RouteHandler;
}
